services:
    postgres-db:
        image: postgis/postgis:16-3.5
        restart: unless-stopped

        environment:
            POSTGRES_DB: linguachat
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

        ports:
            - "5432:5432"

        volumes:
            - postgres-data:/var/lib/postgresql/data

        networks:
            - app-network

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d linguachat"]
            interval: 5s
            timeout: 5s
            retries: 10

    api-server:
        build:
            context: .
            dockerfile: ./backend/Dockerfile

        depends_on:
            postgres-db:
                condition: service_healthy

        env_file:
            - ./backend/.env

        ports:
            - "3000:3000"

        volumes:
            - ./backend:/app/backend
            - ./shared:/app/shared

            # Persist workspace dependencies
            - backend_root_node_modules:/app/node_modules
            - backend_node_modules:/app/backend/node_modules

        networks:
            - app-network

    redis:
        image: redis:7-alpine
        container_name: redis

        restart: unless-stopped

        ports:
            - "6379:6379"

        command: redis-server --save "" --appendonly no

        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5

        networks:
            - app-network

    redisinsight:
        image: redis/redisinsight:latest
        
        container_name: redisinsight

        ports:
        - "5540:5540"

        depends_on:
            - redis
        networks:
            - app-network

    worker:
        build:
            context: .
            dockerfile: ./backend/Dockerfile

        container_name: worker

        working_dir: /app/backend

        command: npm run worker

        env_file:
            - ./backend/.env

        depends_on:
            redis:
                condition: service_healthy
            postgres-db:
                condition: service_healthy

        volumes:
            - ./backend:/app/backend
            - ./shared:/app/shared

            - backend_root_node_modules:/app/node_modules
            - backend_node_modules:/app/backend/node_modules

        networks:
            - app-network

    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile

        depends_on:
            - api-server

        env_file:
            - ./frontend/.env

        ports:
            - "5173:5173"

        volumes:
            - ./frontend:/app/frontend
            - ./shared:/app/shared

            # Persist workspace dependencies
            - frontend_root_node_modules:/app/node_modules
            - frontend_node_modules:/app/frontend/node_modules

        networks:
            - app-network

    adminer:
        image: adminer

        ports:
            - "8080:8080"

        networks:
            - app-network

volumes:
    backend_root_node_modules:
    backend_node_modules:
    frontend_root_node_modules:
    frontend_node_modules:
    postgres-data:

networks:
    app-network:
        driver: bridge
